name: Journey
version: 0.0.2-beta
main: edu.whimc.journey.spigot.JourneySpigot
api-version: 1.17
authors:
  - pietelite
description: A path-optimization Minecraft solution
website: https://whimcproject.web.illinois.edu/
softdepend:
  - WHIMC-Portals
  - Quests
permissions:
  journey.command.admin:
    default: false
    description: Use all journey admin commands
  journey.command.use:
    default: true
    description: Use all journey commands
  journey.command.to.custom.use:
    default: true
    description: Use all commands pertaining to custom destinations
  journey.command.to.surface.use:
    default: true
    description: Use surface command to navigate to the surface of overworld type worlds
  journey.command.to.quest.use:
    default: true
    description: Use quest command to navigate to the next quest destination
  journey.command.to.public.use:
    default: true
    description: Use all commands pertaining to public destinations
  journey.command.to.public.edit:
    default: false
    description: Use commands that edit public destinations
commands:
  journey:
    description: Root of all Journey commands


