name: Indicator
version: @version@
main: edu.whimc.indicator.Indicator
api-version: 1.16
authors:
  - pietelite
description: A path indication plugin
website: https://whimcproject.web.illinois.edu/
softdepend:
  - WHIMC-Portals
  - Quests
permissions:
  indicator.indicator:
    default: false
    description: Root command for indicator subcommands
  indicator.debug:
    default: false
    description: Turn on debug mode
  indicator.trail:
    default: false
  indicator.trail.use:
    default: false
    description: Allows the use of trails
  indicator.trail.manage:
    default: false
    description: Allows the management of trails
commands:
  indicator:
    description: Root indicator command
  trail:
    description: Shows a player a trail to their destination
  endpoint:
    description: Sets an endpoint for a player's trail


